# Binaries will be generated with this name (.elf, .bin, .hex, etc)
PROJ_NAME = firmware
TOOLS_ROOT=../../..

################################################################################
#                   SOURCE FILES TO COMPILE                                    #
################################################################################

# My source file
SRCS   += main.c


################################################################################
#                   SOURCE FILES TO COMPILE                                    #
################################################################################

include $(TOOLS_ROOT)/Projects/Template/Modules/tools.mk
include $(TOOLS_ROOT)/Projects/Template/Modules/Devices/stm32f4-discovery.mk
include $(TOOLS_ROOT)/Projects/Template/Modules/RTOS/freertos.mk
include $(TOOLS_ROOT)/Projects/Template/Modules/targets.mk